import React, { useRef } from "react";
import { useGLTF, OrbitControls } from "@react-three/drei";

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF("/models/iss-model/iss.gltf");
  const group = useRef();
  return (
    <group ref={group} {...props} dispose={null}>
      <OrbitControls enableZoom={false} enablePan={false} />

      <group scale={[30, 30, 30]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.03, 0]}>
            <group position={[0, -0.01, -0.01]}>
              <mesh
                geometry={nodes.primitive_0_1.geometry}
                material={materials.issmod_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_2.geometry}
                material={materials.white}
              />
              <mesh
                geometry={nodes.primitive_0_3.geometry}
                material={materials.material04}
              />
              <mesh
                geometry={nodes.primitive_0_4.geometry}
                material={materials.Material2}
              />
              <mesh
                geometry={nodes.primitive_0_5.geometry}
                material={materials.Material1}
              />
              <mesh
                geometry={nodes.primitive_0_6.geometry}
                material={materials.Material3}
              />
              <mesh
                geometry={nodes.primitive_0_7.geometry}
                material={materials.bluebg}
              />
              <mesh
                geometry={nodes.primitive_0_8.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                geometry={nodes.primitive_0_9.geometry}
                material={materials.isscover_with_Te}
              />
              <mesh
                geometry={nodes.primitive_0_10.geometry}
                material={materials.issleo_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_11.geometry}
                material={materials.issusaf_with_1}
              />
              <mesh
                geometry={nodes.primitive_0_12.geometry}
                material={materials["19___Default"]}
              />
              <mesh
                geometry={nodes.primitive_0_13.geometry}
                material={materials.Default}
              />
              <mesh
                geometry={nodes.primitive_0_14.geometry}
                material={materials.issusa_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_15.geometry}
                material={materials.issred_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_16.geometry}
                material={materials.iss_un_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_17.geometry}
                material={materials.isshand_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_18.geometry}
                material={materials.isscov2_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_19.geometry}
                material={materials.graple_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_20.geometry}
                material={materials.questcov_with_Te}
              />
              <mesh
                geometry={nodes.primitive_0_21.geometry}
                material={materials.issins_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_22.geometry}
                material={materials.metalcon_with_Te}
              />
              <mesh
                geometry={nodes.primitive_0_23.geometry}
                material={materials.isscup_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_24.geometry}
                material={materials.issbs_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_25.geometry}
                material={materials.issesa_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_26.geometry}
                material={materials.issrad_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_27.geometry}
                material={materials.nasda_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_28.geometry}
                material={materials.issusaf_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_29.geometry}
                material={materials.issmb_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_30.geometry}
                material={materials.issbso2_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_31.geometry}
                material={materials.issbso_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_32.geometry}
                material={materials.issku2_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_33.geometry}
                material={materials.issdish_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_34.geometry}
                material={materials.issku1_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_35.geometry}
                material={materials.issku_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_36.geometry}
                material={materials.issb4_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_37.geometry}
                material={materials.isssolar_with_Te}
              />
              <mesh
                geometry={nodes.primitive_0_38.geometry}
                material={materials.primitive_18}
              />
              <mesh
                geometry={nodes.primitive_0_39.geometry}
                material={materials.issb2_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_40.geometry}
                material={materials.isszmod_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_41.geometry}
                material={materials.issb3_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_42.geometry}
                material={materials.issdot_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_43.geometry}
                material={materials.issp2_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_44.geometry}
                material={materials.issb_with_Tex__I}
              />
              <mesh
                geometry={nodes.primitive_0_45.geometry}
                material={materials.isspanel_with_Te}
              />
              <mesh
                geometry={nodes.primitive_0_46.geometry}
                material={materials.d_ring_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_47.geometry}
                material={materials.iss_dcs_with_Tex}
              />
              <mesh
                geometry={nodes.primitive_0_48.geometry}
                material={materials.iss_dc_with_Tex}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/iss-model/iss.gltf");
