import Head from "next/head";

import css from "../css/Home.module.css";

export default function Home() {
  return (
    <div className={css.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
